import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/layout/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#FDFBF7",
        primary: "#721C24",
        "primary-container": "#5A141A",
        "on-primary": "#FFFFFF",
        secondary: "#8C2B34",
        "secondary-container": "#F5EBE6",
        "on-secondary": "#FFFFFF",
        tertiary: "#721C24",
        "tertiary-container": "#F8EAEB",
        "on-tertiary": "#FFFFFF",
        surface: "#FFFFFF",
        "surface-bright": "#FFFFFF",
        "surface-dim": "#F5EFEB",
        "surface-container": "#FAF7F2",
        "surface-container-low": "#FDFBF7",
        "surface-container-lowest": "#FFFFFF",
        "on-surface": "rgba(0, 0, 0, 0.87)",
        "on-surface-variant": "#9E9E9E",
        outline: "#E0E0E0",
        "outline-variant": "#E0E0E0",
        error: "#B33A3A",
        "on-error": "#FFFFFF",
        // Dolores UI Palette tokens
        card: "#FFFFFF",
        hero: "#721C24",
        "hero-light": "#721C24",
        heading: "#721C24",
        body: "rgba(0, 0, 0, 0.87)",
        muted: "#9E9E9E",
        border: "#E0E0E0",
        accent: "#721C24",
        // Coffee theme aliases
        "coffee-cream": "#FDFBF7",
        "coffee-latte": "#F5EBE6",
        "coffee-roast": "#721C24",
        "coffee-espresso": "#5A141A",
        "coffee-bronze": "#8C2B34",
        "coffee-gold": "#A2323D",
        "coffee-mocha": "#721C24",
        "coffee-steam": "#E0E0E0",
      },
      fontFamily: {
        sans: ["var(--font-hanken)", "sans-serif"],
        mono: ["var(--font-hanken)", "sans-serif"],
        serif: ["var(--font-playfair)", "Georgia", "serif"],
      },
      spacing: {
        base: "8px",
        "container-padding-mobile": "1rem",
        "container-padding-desktop": "2.5rem",
        gutter: "1.5rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
